version: '2'
services:
  helloworld:
    privileged: true
    image: hello-world
    labels:
      io.rancher.scheduler.affinity:host_label: monitor=true
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.global: 'true'
