version: '2'
services:
  loadbalancer:
    image: rancher/lb-service-haproxy:v0.9.6
    ports:
    - 80:80/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: vip=true
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
  uri-rancher:
    image: rancher/external-service

