version: '2'
services:
  loadbalancer:
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        global
                log 127.0.0.1   local0
                log 127.0.0.1   local1 notice
                maxconn 4096
                daemon

        defaults
                log     global
                mode    http
                option  httplog
                option  dontlognull
                option  forwardfor
                option  http-server-close
        #        stats   enable
        #        stats   auth someuser:somepassword
        #        stats   uri /haproxyStats

        frontend http-in
                bind *:80

                # Define hosts
                acl host_jenkins hdr(host) -i servodroid.com/jenkins

                ## figure out which one to use
                use_backend jenkins_backend if host_jenkins

        backend jenkins_backend
                #redirect scheme https if !{ ssl_fc }
                # balance leastconn
                #option httpclose
                option forwardfor
                cookie JSESSIONID prefix
                server node1 jenkins:8081 cookie A check
      port_rules:
      - path: ''
        priority: 1
        protocol: http
        service: websites/site
        source_port: 80
        target_port: 80
      - path: /api
        priority: 2
        protocol: http
        service: websites/api
        source_port: 80
        target_port: 3737
      - hostname: ''
        path: /grafana
        priority: 3
        protocol: http
        service: monitor/grafana
        source_port: 80
        target_port: 3000
      - backend_name: ''
        hostname: ''
        path: /rancher
        priority: 4
        protocol: http
        service: uri-rancher
        source_port: 80
        target_port: 8080
      - backend_name: jenkins_backend
        path: /jenkins
        priority: 5
        protocol: http
        service: continuousprocess/jenkins
        source_port: 80
        target_port: 8081
      - path: /prometheus
        priority: 6
        protocol: http
        service: monitor/prometheus
        source_port: 80
        target_port: 9090
      - backend_name: ''
        path: /tobi/rabbitmq
        priority: 7
        protocol: http
        service: tobi/rabbitmq
        source_port: 80
        target_port: 15672
      - path: /tobi/async
        priority: 8
        protocol: http
        service: tobi/async
        source_port: 80
        target_port: 9001
      - path: /tobi/database
        priority: 9
        protocol: http
        service: tobi/database
        source_port: 80
        target_port: 5432
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  uri-rancher:
    external_ips:
    - 93.118.34.204
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000

