version: '2'
services:
  async:
    privileged: true
    image: tobi.async:latest
    ports:
    - 9001:9001/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: tobi=true
      io.rancher.scheduler.global: 'true'
  tobi-lb:
    image: rancher/lb-service-haproxy
    ports:
    - 5454:5454/tcp
    expose:
    - 15672:15672/tcp
    - 5672:5672/tcp
    - 5673:5673/tcp
    - 9200:9200/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: vip=true
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
  postgres-data:
    privileged: true
    image: busybox
    volumes:
    - pgdata:/var/lib/postgresql/data/pgdata
    labels:
      io.rancher.scheduler.affinity:host_label: tobi=true
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.global: 'true'
  rabbitmq:
    privileged: true
    image: tobi.rabbitmq:latest
    ports:
    - 15672:15672/tcp
    - 5672:5672/tcp
    - 5673:5673/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: tobi=true
      io.rancher.scheduler.global: 'true'
  postgres:
    privileged: true
    image: tobi.postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: t0b1PWD!!!
      POSTGRES_USER: tobi
    volumes_from:
    - postgres-data
    ports:
    - 5454:5432
    labels:
      io.rancher.scheduler.affinity:host_label: tobi=true
      io.rancher.sidekicks: postgres-data
      io.rancher.scheduler.global: 'true'
